### ISSUE TITLE
session-memory-store replacement

### ISSUE THREAD

**Issue by roccomuso** [innovajs/token-session#1]
I saw you using a no more mantained in-memory store module for the express-session.

I recommend to switch to a fully-tested one, check it out: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by gustter** [comment]
Hi. Thanks for your suggestion. Appreciate it. Please open a Pull Request with the proposed change and add your comparison of advantages of your module over the one used? Thanks again.
